[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0x3ddbd9"
index = 16

[[colors.indexed_colors]]
color = "0xff7eb6"
index = 17

[colors.bright]
black = "0x484848"
blue = "0x8cb6ff"
cyan = "0x52bdff"
green = "0x46c880"
magenta = "0xc8a5ff"
red = "0xf16da6"
white = "0xe4e4e5"
yellow = "0x2dc7c4"

[colors.normal]
black = "0x282828"
blue = "0x78a9ff"
cyan = "0x33b1ff"
green = "0x25be6a"
magenta = "0xbe95ff"
red = "0xee5396"
white = "0xdfdfe0"
yellow = "0x08bdba"

[colors.primary]
background = "0x161616"
foreground = "0xf2f4f8"

[env]
TERM = "xterm-256color"

[font.normal]
family = "mononoki"

[[schemes.carbonfox.indexed_colors]]
color = "0x3ddbd9"
index = 16

[[schemes.carbonfox.indexed_colors]]
color = "0xff7eb6"
index = 17

[schemes.carbonfox.bright]
black = "0x484848"
blue = "0x8cb6ff"
cyan = "0x52bdff"
green = "0x46c880"
magenta = "0xc8a5ff"
red = "0xf16da6"
white = "0xe4e4e5"
yellow = "0x2dc7c4"

[schemes.carbonfox.normal]
black = "0x282828"
blue = "0x78a9ff"
cyan = "0x33b1ff"
green = "0x25be6a"
magenta = "0xbe95ff"
red = "0xee5396"
white = "0xdfdfe0"
yellow = "0x08bdba"

[schemes.carbonfox.primary]
background = "0x161616"
foreground = "0xf2f4f8"

[schemes.melange-dark.bright]
black = "0x867462"
blue = "0xa3a9ce"
cyan = "0x89b3b6"
green = "0x85b695"
magenta = "0xcf9bc2"
red = "0xd47766"
white = "0xece1d7"
yellow = "0xebc06d"

[schemes.melange-dark.normal]
black = "0x34302c"
blue = "0x7f91b2"
cyan = "0x7b9695"
green = "0x78997a"
magenta = "0xb380b0"
red = "0xbd8183"
white = "0xc1a78e"
yellow = "0xe49b5d"

[schemes.melange-dark.primary]
background = "0x292522"
foreground = "0xece1d7"

[schemes.tokyo-night.bright]
black = "0x444b6a"
blue = "0x7da6ff"
cyan = "0x0db9d7"
green = "0xb9f27c"
magenta = "0xbb9af7"
red = "0xff7a93"
white = "0xacb0d0"
yellow = "0xff9e64"

[schemes.tokyo-night.normal]
black = "0x32344a"
blue = "0x7aa2f7"
cyan = "0x449dab"
green = "0x9ece6a"
magenta = "0xad8ee6"
red = "0xf7768e"
white = "0x787c99"
yellow = "0xe0af68"

[schemes.tokyo-night.primary]
background = "0x1a1b26"
foreground = "0xa9b1d6"

[schemes.tokyo-night-storm.bright]
black = "0x444b6a"
blue = "0x7da6ff"
cyan = "0x0db9d7"
green = "0xb9f27c"
magenta = "0xbb9af7"
red = "0xff7a93"
white = "0xacb0d0"
yellow = "0xff9e64"

[schemes.tokyo-night-storm.normal]
black = "0x32344a"
blue = "0x7aa2f7"
cyan = "0x449dab"
green = "0x9ece6a"
magenta = "0xad8ee6"
red = "0xf7768e"
white = "0x9699a8"
yellow = "0xe0af68"

[schemes.tokyo-night-storm.primary]
background = "0x24283b"
foreground = "0xa9b1d6"
